---
title: '1406'
author: "Valentina Nauchi"
date: "2024-06-14"
output: html_document
---

```{r}
setwd("C:/1406")
```

```{r}
library(rio)
data1 = import("Latinobarometro2023.rdata")
data1
```

```{r}
data1$idenpa=as.factor(data1$idenpa)
data1$idenpa=factor(data1$idenpa,
                levels = levels(data1$idenpa),
                labels = c("Argentina", "Bolivia", "Brasil", "Colombia", "Costa Rica" , "Chile" , "Ecuador", "El Salvador", "Guatemala", "Honduras", "México", "Nicaragua", "Panamá", "Paraguay", "Perú", "Uruguay", "Venezuela"),
                ordered = F)
```

```{r}
library(dplyr)
peru <- data1 %>%
filter(idenpa=="Perú")
```

```{r}
names(peru)=gsub(pattern = "NUMENTRE",
replacement = "NumEntre",x = names(peru))
```

```{r}
table(peru$numentre)
```

#VARIABLES INDEPENDIENTES 

```{r}
names(peru)=gsub(pattern = "P11STGBS.A",
                           replacement = "satis_dem",
                           x = names(peru))
```

```{r}
table(peru$satis_dem)
```
```{r}
library(dplyr)
peru = peru %>%
  filter(satis_dem %in% c(1,2,3,4))
```

```{r}
table(peru$satis_dem)
```
```{r}
names(peru)=gsub(pattern = "P10STGB",
                           replacement = "creencias",
                           x = names(peru))
```


```{r}
library(dplyr)
peru = peru %>%
  filter(creenciasS %in% c(1,2,3))
```

#VARIABLES DE CONTROL 
#ETNIA 

```{r}
names(peru)=gsub(pattern = "S7",
                           replacement = "etnia",
                           x = names(peru))
```

```{r}
library(dplyr)
peru = peru %>%
  filter(etnia %in% c(1,2,3,4,5,6,7))
table(peru$etnia)
```
#CLASE SOCIAL - ESTRATO
```{r}
names(peru)=gsub(pattern = "S2",
                           replacement = "estrato",
                           x = names(peru))
```

```{r}
library(dplyr)
peru = peru %>%
  filter(estrato %in% c(1,2,3,4,5))
table(peru$estrato)
```
#PARTIDO POLITICO - FAMPART

```{r}
names(peru)=gsub(pattern = "fampart",
                           replacement = "partido_pol",
                           x = names(peru))
```

```{r}
table(peru$partido_pol)
```


```{r}
library(dplyr)
peru = peru %>%
  filter(partido_pol %in% c(0,20,30,40,50,60,70,80,98))
```

```{r}
table(peru$partido_pol)
```
#VARIABLE DEPENDIENTE - CONFIANZA EN LAS INSTITUCIONES 
```{r}
names(peru)=gsub(pattern = "P13ST.D",
                           replacement = "Congreso",
                           x = names(peru))
```

```{r}
names(peru)=gsub(pattern = "P13ST.E",
                           replacement = "Gobierno",
                           x = names(peru))
```

```{r}
names(peru)=gsub(pattern = "P13ST.G",
                           replacement = "Partidos_Politicos",
                           x = names(peru))
```

```{r}
names(peru)=gsub(pattern = "P13ST.I",
                           replacement = "Presidente",
                           x = names(peru))
```

#DATOS PERDIDOS 
```{r}
total_na <- sum(is.na(peru))
print(paste("Total de valores NA:", total_na))
```
```{r}
table(peru$Congreso)
```
```{r}
library(dplyr)
peru = peru %>%
  filter(Congreso %in% c(1,2,3,4))
table(peru$Congreso)
```
```{r}
table(peru$Gobierno)
```
```{r}
library(dplyr)
peru = peru %>%
  filter(Gobierno %in% c(1,2,3,4))
table(peru$Gobierno)
```
```{r}
table(peru$Partidos_Politicos)
```
```{r}
library(dplyr)
peru = peru %>%
  filter(Partidos_Politicos %in% c(1,2,3,4))
table(peru$Partidos_Politicos)
```

```{r}
table(peru$Presidente)
```
```{r}
library(dplyr)
peru = peru %>%
  filter(Presidente %in% c(1,2,3,4))
table(peru$Presidente)
```

```{r}
library(writexl)

country2 <- peru [,c("numentre","satis_dem", "creenciasS", "etnia", "estrato", "partido_pol", "Congreso", "Gobierno", "Partidos_Politicos", "Presidente")]

write_xlsx(country2, "country3.xlsx")
```


#EFA 2 



```{r}
names(country2)
```

```{r}
dontselect=c("numentre","satis_dem","creenciasS","etnia","estrato", "partido_pol")
select=setdiff(names(country2),dontselect) 
mipais1=country2[,select]

# usaremos:
library(magrittr)
head(mipais1,10)%>%
    rmarkdown::paged_table()
```
#Calculemos las correlaciones entre todas las variables

```{r}
mipais1$Congreso= as.numeric(mipais1$Congreso)
mipais1$Gobierno= as.numeric(mipais1$Gobierno)
mipais1$Partidos_Politicos= as.numeric(mipais1$Partidos_Politicos)
mipais1$Presidente= as.numeric(mipais1$Presidente)
```

```{r}
str(mipais1)
```


```{r}
library(polycor)
```

```{r}
corMatrix=polycor::hetcor(mipais1)$correlations
```

```{r}
round(corMatrix,2)
```
```{r}
library(ggcorrplot)

ggcorrplot(corMatrix)
```

```{r}
library(psych)
psych::KMO(corMatrix) 
```
```{r}
cortest.bartlett(corMatrix,n=nrow(mipais1))$p.value>0.05
```
```{r}
library(matrixcalc)

is.singular.matrix(corMatrix)
```
```{r}
fa.parallel(mipais1, fa = 'fa',correct = T,plot = F)
```
```{r}
library(GPArotation)
resfa <- fa(mipais1,
            nfactors = 1,
            cor = 'mixed',
            rotate = "varimax", #oblimin?
            fm="minres")
print(resfa$loadings)
```

```{r}
sort(resfa$communality)
```
```{r}
regresFactors=as.data.frame(resfa$scores)%>%head()
```





